cxf:
  path: /service
spring:
  application:
    name: shelter-service
  datasource:
    url: jdbc:h2:~/testdb;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      path: /h2-console
      settings:
        trace: true
      enabled: true
logging:
  level:
    org:
      springframework:
        web:
          logging:
            LogLevel: trace
        boot:
          logging:
            LogLevel: trace